<?php
/**
 * URL validation and SSRF protection.
 *
 * @package AIPageDesigner
 */

namespace AIPageDesigner\Security;

use WP_Error;

defined( 'ABSPATH' ) || exit;

/**
 * Validates provider endpoints, remote media URLs and links generated by the model.
 */
final class UrlValidator {

	/**
	 * Whether private/loopback endpoints (for example a local model server) are allowed.
	 *
	 * Disabled by default. Only a site owner can enable it, from wp-config.php:
	 * define( 'AIPD_ALLOW_LOCAL_ENDPOINTS', true );
	 *
	 * @return bool
	 */
	public static function local_endpoints_allowed() {
		$allowed = defined( 'AIPD_ALLOW_LOCAL_ENDPOINTS' ) && AIPD_ALLOW_LOCAL_ENDPOINTS;

		/**
		 * Filters whether private network AI endpoints may be used.
		 *
		 * @since 1.0.0
		 *
		 * @param bool $allowed Whether local endpoints are allowed.
		 */
		return (bool) apply_filters( 'aipd_allow_local_endpoints', $allowed );
	}

	/**
	 * Validates an AI provider base URL.
	 *
	 * @param string $url Raw URL.
	 * @return string|WP_Error Normalized URL without trailing slash, or error.
	 */
	public static function validate_endpoint( $url ) {
		$url = trim( (string) $url );
		if ( '' === $url || strlen( $url ) > 2048 ) {
			return new WP_Error( 'aipd_invalid_url', __( 'Enter a valid API URL.', 'ai-page-designer' ) );
		}

		$parts = wp_parse_url( $url );
		if ( ! is_array( $parts ) || empty( $parts['scheme'] ) || empty( $parts['host'] ) ) {
			return new WP_Error( 'aipd_invalid_url', __( 'Enter a valid API URL.', 'ai-page-designer' ) );
		}

		$scheme = strtolower( $parts['scheme'] );
		$local  = self::local_endpoints_allowed();

		if ( isset( $parts['user'] ) || isset( $parts['pass'] ) ) {
			return new WP_Error( 'aipd_invalid_url', __( 'The API URL must not contain a user name or password.', 'ai-page-designer' ) );
		}
		if ( isset( $parts['query'] ) || isset( $parts['fragment'] ) ) {
			return new WP_Error( 'aipd_invalid_url', __( 'The API URL must not contain a query string or fragment.', 'ai-page-designer' ) );
		}
		if ( 'https' !== $scheme && ! ( $local && 'http' === $scheme ) ) {
			return new WP_Error( 'aipd_insecure_url', __( 'The API URL must use HTTPS.', 'ai-page-designer' ) );
		}
		if ( isset( $parts['path'] ) && preg_match( '#(^|/)\.\.?(/|$)#', $parts['path'] ) ) {
			return new WP_Error( 'aipd_invalid_url', __( 'The API URL path is not allowed.', 'ai-page-designer' ) );
		}

		if ( ! $local && ! self::is_public_host( $parts['host'] ) ) {
			return new WP_Error( 'aipd_private_url', __( 'The API URL points to a private or reserved network address, which is blocked for security reasons.', 'ai-page-designer' ) );
		}

		$normalized = $scheme . '://' . strtolower( $parts['host'] );
		if ( isset( $parts['port'] ) ) {
			$normalized .= ':' . (int) $parts['port'];
		}
		if ( isset( $parts['path'] ) ) {
			$normalized .= $parts['path'];
		}

		return untrailingslashit( esc_url_raw( $normalized, array( 'http', 'https' ) ) );
	}

	/**
	 * Resolves a host and checks that every address is public.
	 *
	 * @param string $host Host name or IP literal.
	 * @return bool
	 */
	public static function is_public_host( $host ) {
		$host = strtolower( trim( $host, '[]' ) );
		if ( '' === $host || 'localhost' === $host || '.localhost' === substr( $host, -10 ) ) {
			return false;
		}

		if ( filter_var( $host, FILTER_VALIDATE_IP ) ) {
			return self::is_public_ip( $host );
		}

		/**
		 * Filters the resolved IPs for a host. Used by tests to avoid real DNS.
		 *
		 * @since 1.0.0
		 *
		 * @param string[]|null $ips  Pre-resolved addresses, or null to use DNS.
		 * @param string        $host Host name.
		 */
		$ips = apply_filters( 'aipd_resolve_host', null, $host );
		if ( null === $ips ) {
			$ips = gethostbynamel( $host );
		}
		if ( empty( $ips ) || ! is_array( $ips ) ) {
			return false;
		}

		foreach ( $ips as $ip ) {
			if ( ! self::is_public_ip( $ip ) ) {
				return false;
			}
		}
		return true;
	}

	/**
	 * Whether an IP address is outside private and reserved ranges.
	 *
	 * @param string $ip IP address.
	 * @return bool
	 */
	public static function is_public_ip( $ip ) {
		return false !== filter_var( $ip, FILTER_VALIDATE_IP, FILTER_FLAG_NO_PRIV_RANGE | FILTER_FLAG_NO_RES_RANGE );
	}

	/**
	 * Sanitizes a link produced by the model or a template.
	 *
	 * Allows http(s), mailto, tel, in-page anchors and site-relative paths.
	 * Anything else (javascript:, data:, protocol-relative, etc.) becomes '#'.
	 *
	 * @param string $url Raw URL.
	 * @return string
	 */
	public static function sanitize_link( $url ) {
		$url = trim( (string) $url );
		if ( '' === $url ) {
			return '#';
		}
		if ( preg_match( '/^#[A-Za-z][A-Za-z0-9_-]{0,63}$/', $url ) || '#' === $url ) {
			return $url;
		}
		if ( '/' === $url[0] ) {
			if ( 0 === strpos( $url, '//' ) || false !== strpos( $url, '\\' ) || preg_match( '#(^|/)\.\.(/|$)#', $url ) ) {
				return '#';
			}
			$clean = esc_url_raw( home_url( $url ) );
			return '' === $clean ? '#' : wp_make_link_relative( $clean );
		}
		$clean = esc_url_raw( $url, array( 'http', 'https', 'mailto', 'tel' ) );
		return '' === $clean ? '#' : $clean;
	}

	/**
	 * Validates a remote image URL before a user-approved sideload.
	 *
	 * @param string $url Raw URL.
	 * @return string|WP_Error
	 */
	public static function validate_remote_image( $url ) {
		$url   = esc_url_raw( trim( (string) $url ), array( 'https' ) );
		$parts = $url ? wp_parse_url( $url ) : false;
		if ( ! $parts || empty( $parts['host'] ) || isset( $parts['user'] ) || isset( $parts['pass'] ) ) {
			return new WP_Error( 'aipd_invalid_image_url', __( 'The image URL is not valid. Only HTTPS image URLs are accepted.', 'ai-page-designer' ) );
		}
		if ( ! self::is_public_host( $parts['host'] ) ) {
			return new WP_Error( 'aipd_private_url', __( 'The image URL points to a private or reserved network address.', 'ai-page-designer' ) );
		}
		$path = isset( $parts['path'] ) ? strtolower( $parts['path'] ) : '';
		if ( ! preg_match( '/\.(jpe?g|png|gif|webp)$/', $path ) ) {
			return new WP_Error( 'aipd_invalid_image_type', __( 'Only JPEG, PNG, GIF and WebP images can be imported.', 'ai-page-designer' ) );
		}
		return $url;
	}
}
